### GET all courses
GET http://localhost:3000/api/courses
Content-Type: application/json

### GET course by ID
GET http://localhost:3000/api/courses/6930f960855007aa6fa71657
Content-Type: application/json

### CREATE a new course (POST)
POST http://localhost:3000/api/courses
Content-Type: application/json

{
  "courseId": 301,
  "name": "Environmental Studies: Climate & Sustainability",
  "code": "ENV120",
  "credits": 3,
  "department": "Science",
  "isActive": true,
  "maxStudents": 28,
  "schedule": {
    "day": "Tuesday",
    "startTime": "11:00",
    "endTime": "13:00"
  },
  "prerequisites": []
}

### UPDATE a course (PUT)
PUT http://localhost:3000/api/courses/6934c5ff9bf66a3c7ac6d8e2
Content-Type: application/json

{
  "courseId": 301,
  "name": "Environmental Studies: Climate & Sustainability",
  "code": "ENV120",
  "credits": 4,
  "department": "Science",
  "isActive": true,
  "maxStudents": 32,
  "schedule": {
    "day": "Tuesday",
    "startTime": "15:00",
    "endTime": "17:00"
  },
  "prerequisites": []
}


### DELETE a teacher (DELETE)
DELETE http://localhost:3000/api/courses/6934c5ff9bf66a3c7ac6d8e2
Content-Type: application/json